apiVersion: v1
kind: Service
metadata:
{{- if .Values.data.service.annotations }}
  annotations:
{{ toYaml .Values.data.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "influxdb-cluster.fullname" . }}-data-headless
  labels:
    influxdb.cluster/component: data-headless
    {{- include "influxdb-cluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8086
    protocol: TCP
    name: http
  - port: 8088
    protocol: TCP
    name: rpc
  - port: 2003
    # Graphite supports TCP and UDP,
    # so this should __maybe__ be configurable
    # Though most use TCP
    protocol: TCP
    name: graphite
  - port: 4242
    protocol: TCP
    name: opentsdb
    # LoadBalancer service type only allows for one protocol
    # disbaling UDP ports
  - port: 25826
    protocol: UDP
    name: collectd
  - port: 8089
    protocol: UDP
    name: udp
  selector:
    influxdb.cluster/component: data
{{- include "influxdb-cluster.selectorLabels" . | nindent 4 }}
