apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "influxdb-cluster.fullname" . }}-data
  labels:
    app.kubernetes.io/component: data
    {{- include "influxdb-cluster.labels" . | nindent 4 }}
data:
  influxdb.conf: |+
    bind-address = ":8088"
    reporting-disabled = false

    [http]
    {{ if .Values.data.https.enabled }}
    https-enabled = true

    https-certificate = "/var/run/secrets/tls/tls.crt"
    https-private-key = "/var/run/secrets/tls/tls.key"

    {{ end }}

    {{ if .Values.data.flux.enabled }}
    flux-enabled = true
    {{ end }}

    [coordinator]
    {{ if .Values.data.https.enabled }}
    https-enabled = true

    https-certificate = "/var/run/secrets/tls/tls.crt"
    https-private-key = "/var/run/secrets/tls/tls.key"

    {{ if .Values.data.https.insecure }}
    https-insecure-tls = true
    {{ end }}
    {{ end }}

    [meta]
      dir = "/var/lib/influxdb/meta"

      {{ if and .Values.meta.https.enabled }}
      meta-tls-enabled = true

      {{ if .Values.meta.https.insecure }}
      meta-insecure-tls = true
      {{ end }}

      {{ end }}

    [hinted-handoff]
      dir = "/var/lib/influxdb/hh"

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
