apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "influxdb-cluster.fullname" . }}-meta
  labels:
    app.kubernetes.io/component: meta
    {{- include "influxdb-cluster.labels" . | nindent 4 }}
data:
  influxdb-meta.conf: |+
    bind-address = ":8091"
    reporting-disabled = false

    [meta]
      dir = "/var/lib/influxdb/meta"

      {{ if .Values.meta.https.enabled }}
      https-enabled = true

      https-certificate = "/var/run/secrets/tls/tls.crt"
      https-private-key = "/var/run/secrets/tls/tls.key"

      {{ if .Values.meta.https.insecure }}
      https-insecure-tls = true
      {{ end }}

      {{ end }}

      {{ if and .Values.data.https.enabled }}
      data-use-tls = true

      {{ if .Values.data.https.insecure }}
      data-insecure-tls = true
      {{ end }}

      {{ end }}
