apiVersion: v1
kind: Service
metadata:
{{- if .Values.meta.service.annotations }}
  annotations:
{{ toYaml .Values.meta.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "influxdb-cluster.fullname" . }}-meta
  labels:
    influxdb.cluster/component: meta
    {{- include "influxdb-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.meta.service.type }}
{{- if and (eq "ClusterIP" .Values.meta.service.type) .Values.meta.service.clusterIP }}
  clusterIP: {{ .Values.meta.service.clusterIP }}
{{- end }}
  publishNotReadyAddresses: true
  ports:
  - port: 8089
    protocol: TCP
    name: raft
  - port: 8091
    protocol: TCP
    name: http
{{- if and (eq "NodePort" .Values.meta.service.type) .Values.meta.service.nodePort }}
    nodePort: {{ .Values.meta.service.nodePort }}
{{- end }}
  selector:
    influxdb.cluster/component: meta
    {{- include "influxdb-cluster.selectorLabels" . | nindent 4 }}
{{- if .Values.meta.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.meta.service.loadBalancerIP }}
{{- end }}
{{- if .Values.meta.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.meta.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.meta.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.meta.service.externalTrafficPolicy }}
{{- end }}
